### PR TITLE
Update cgle-c++ content.

### PR DESCRIPTION
**Pull request by ghost**
Updated from the older version Linas initially uploaded. Comes with VS17 project file and pre-compiled Windows binaries. Check project settings for SDK/toolset version used to compile the binaries.

Documentation is still a work in progress. Hope to have it finished soon.

### CODE REVIEW

**Comment by linas** [comment]
OK, I can merge this, but I have to ask: are you sure?  There's something like 537 new files here, they all look like automatically generated garbage from doxygen, and what-not.    Git is intended for use by humans, for humans, containing human-readable data that humans would edit.  Just about everything here is not human readable -- its generated by doxygen and whatever other tools you are using.   Therefore, its not really appropriate to check these in.

So, I'll ask again: are you sure? Cause this seems to create a mess, where no mess existed before...

**Comment by ghost** [comment]
Hi, Linas –

 

Well, it’s up to you. How about if I put the whole of the docs in a .zip, and place that in the ‘Help’ folder instead? That would simplify the file structure. It’d be easier to deal with updates, too.

 

DR

**Comment by linas** [comment]
Well, the whole point of a source-control system is that it stores ... source.  Therefore, fundamentally, zip files are never-ever placed into a source-control system, the same way you would never place libraries or executables into the system.    What you would check in would be any hand-written files, e.g. hand-written documentation, and any shell scripts, build files, config files, etc. that are needed to create that documentation dump.

Github is not a system for publishing websites: there are other ways to do that. github does have a wiki that we could set up for this, but I don't beleive it provides a way to publish docbook output.

**Comment by ghost** [comment]
Hey –

 

OK, let me work on it. I’ll strip out all the help content, and if I can get all the absolute paths out of the doxygen config file, I’ll just post that, instead.

 

I’ll get on it as soon as I have a bite to eat.

 

Sorry if I’m being a bit thick.

 

 

DR

**Comment by linas** [comment]
I'm now seeing changes to source code here.  Can you put this into a different branch, different pull request?   Currently, this is not reviewable.

The point of having distinct branches, distinct pull requests is that each one represents a coherent batch of work, a collection of changes that "go together."  That allows them to be reviewed for correctness, completeness - if there are bugs, they can be spotted.  But if you provide a big jumble .. who knows. Its just a big jumble.

So for example, changes that change only the version number would be completely separate, developed in their own branch.This makes them easy, almost trivial to review.   Similarly, changes to whitespace.  Then when there are actual changes to function, to the code, they now become easy to read and understand, because they are not mixed in with other minor changes.   Each pull request should be single satisfying meal, a single plate of changes, not a banquet hall after a big party.  

Based on experience, they are usually a dozen to a few hundred lines of code, touching a few up to a dozen files.   Here I have 65 thousand lines of code changed !! and 77 files changed, its not controllable. Its not "source code control" if it can't be controlled.

**Comment by ghost** [comment]
Hey –

 

I’m not sure what you’re referring to. I was just in the process of removing all the doxygen-generated help content and replacing it with the doxygen config file. I was going to issue a new pull request when I was finished – I was under the impression that you had refused the last one.

 

And I haven’t touched anything outside of the cgle-c++ folder – at least not intentionally.

 

DR

**Comment by ghost** [comment]
Hey –

 

Just to clarify, yes, there are significant differences to the code in the Harvey-birdman/glextrusion/cgle-c++ folder when compared to that in linas/glextrusion/cgle-c++. I really don’t care to track those  changes – I’d prefer to simply replace the content you originally uploaded. 

 

This became a bit more complicated with the need to delete out the doxygen-created content. 

 

But that’s where it is. The material in my copy of linas/glextrusion should differ only in the glec-c++ folder. And that new content was intended to replace, not provide  continuous path, from the material you’d originally uploaded into that folder.

 

So anyway, should I issue another pull request?

 

DR

**Comment by linas** [comment]
Well, you have been pushing additional commits onto this branch, on top of earlier commits, in a very linear fashion.  So what I see is a lot of churn - commits that add stuff, and then remove stuff.  So far, everything you've been doing has all been going into this pull request, and not some other one. 

The intent of having branches is to avoid this kind of undo/redo operations, to avoid some of the issues that  linear sequences force you into.

**Comment by linas** [comment]
If you want to make a big blanket change to `cgle-c++`, then fine, do that. I'm just saying that big blanket changes are hard to understand, and so that kind-of defeats the whole point of source control.

Also -- you are welcome to make changes to the other code -- that is just fine, and even encouraged. But those changes need to be reviewable, understandable.  This is not about territoriality, but about process: git is a tool for creating high-quality code, but if you misuse the tool, that makes it pointless.  Its like using a table saw to hammer nails. You can do it, but you'll have a dinged-up table saw at the end.

**Comment by ghost** [comment]
Hmmm. Is there any way to discard the current fork? I could just start fresh and avoid the addition and subsequent deletion of all the doxygen related stuff…

 

 

DR

**Comment by linas** [comment]
Well, you wouldn't discard the fork. That's a pain. You'd go back to an older commit, and create a branch there.   So, for example, to see the history on some given branch:
```
git log
```
Then review that history of commits.  Pick the one you want to restart at: for example:
```
git checkout 4e0dcf8  
git checkout -b "mynewbranch"
```
then hack away, `git commit` hack, `git commit` etc.  Then
```
git push origin mynewbranch
```
then from the website, create a new pull request.   FWIW, you can create the new pull request for me, or for yourself, or anyone else who is interested: a pull request is a kind of "please make these changes to your code" - its a peer-to-peer thing, rather than a master-slave thing.

**Comment by linas** [comment]
If you click on "insights" and then "network", you can see the branching structure.  Its super-simple, just right now

**Comment by ghost** [comment]
Linas –

 

 

This is getting to be more than I want to deal with. Please just remove me ads a contributor and delete the content.

 

Thanks –

 

DR

**Comment by linas** [comment]
OK pull request #7 and #8 merges in a collapsed version of above. I could not cherry pick, as the the tree was partly blown away.

**Pull request closed without merging**
