### PR TITLE
modify for building on Windows

### PR DESCRIPTION
**Pull request by yoshikawa-hiroyuki**
- README.md: add compile option "-DOPENGL_10=1" and change the target name.
- ms-visual-c/gle/gle.dsp: add "ex_alpha.c" to source list,
  modify the path of gle.h, and add compile option "-DOPENGL_10=1"

### CODE REVIEW

**Comment by linas** [comment]
Wow, thanks!

**Comment by yoshikawa-hiroyuki** [comment]
Hi, Linas –
I modify README.md and ms-visual-c/gle/gle.dsw for building on WIndows.
Please check it.

**Comment by linas** [comment]
More is possible --
* delete mention of os/2
* maybe 32 and 64-bit works?
* ... general modernization to modern coding style.

**Comment by yoshikawa-hiroyuki** [comment]
Well, yes. I tried 32 and 64 bit Windows, with using WisualStudio 2013 / 2015, it was fine.

**Comment by yoshikawa-hiroyuki** [comment]
Thanks :-)

**Pull request merged**
